apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: ia-analise-de-precos-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "gitlab"
      params:
        - name: "secretRef"
          value:
            secretName: git-auth
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
  bindings:
    - ref: ia-analise-de-precos
  template:
    ref: ia-analise-de-precos
